when:
  - event: [ manual ]
    evaluate: 'LATEST_TAG != ""'

variables:
  - &image_name 'quay.krd.sh/krd/woodpecker-sonatype-nexus'
  - &ext_image_name 'docker.io/rockdrilla/woodpecker-sonatype-nexus'
  - &skopeo_image 'quay.krd.sh/quay_io/containers/skopeo:v1.15.2'

## NB: ${variable} expressions are subject to pre-processing.
## ref: https://woodpecker-ci.org/docs/usage/environment

steps:

  - name: verify-registry-credentials
    image: *skopeo_image
    environment:
      GOMAXPROCS: "4"
      MALLOC_ARENA_MAX: "4"
    secrets: [ REGISTRY_AUTH ]
    commands:
      - .ci/registry-login.sh quay.krd.sh docker.io

  - name: image-sync-latest
    image: *skopeo_image
    environment:
      GOMAXPROCS: "4"
      MALLOC_ARENA_MAX: "4"
      ##
      IMAGE_NAME: *image_name
      EXT_IMAGE_NAME: *ext_image_name
    commands:
      - .ci/sync-latest.sh

## personal tweaks :)
labels:
  network: dmz
