when:
  - event: [ manual ]
    evaluate: 'LATEST_TAG != ""'

variables:
  - &image_name 'quay.krd.sh/krd/woodpecker-sonatype-nexus'
  - &skopeo_image 'quay.io/containers/skopeo:v1.21.0'

## NB: ${variable} expressions are subject to pre-processing.
## ref: https://woodpecker-ci.org/docs/usage/environment

steps:

  - name: verify-registry-credentials
    image: *skopeo_image
    environment:
      GOMAXPROCS: "4"
      MALLOC_ARENA_MAX: "4"
      REGISTRY_AUTH:
        from_secret: REGISTRY_AUTH
    commands:
      - .ci/registry-login.sh docker.io

  - name: image-sync-latest
    image: *skopeo_image
    environment:
      GOMAXPROCS: "4"
      MALLOC_ARENA_MAX: "4"
      ##
      IMAGE_NAME: *image_name
    commands:
      - .ci/sync-latest.sh

## personal tweaks :)
labels:
  network: dmz
